apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAkOhv2PLqtIq674jrdz+8ly068YK9TkWxWZjd5BArSZfXvMVUIS9/xv5MX/lYlEEud0yKBa6cGXyqVmINtgWggWM7PMO4sCSLgugKBHu1AKRTINvTL37yB0mGINqr72p3YGDDj+gGkaGDEq5b74J41SrP3sVUhyI9B44ObL9YZNBWpJVC5c4Z0N/TRae9dnpjD74yTzecMEn80y6ePYdXVA3JiXsAP9Af3hX9nsEQg7sJKFdkj01UbRxLTVp12s0uYogsXHjqVcA98MG1lXQwsbrUJ/LJU2Qnoi0akwovNMw4gE7OmNIJxMWxCD2pYTq/MUGwD4TwRkjDDFUTY6Mii31nC32aDd+NmTnJQmSdN8bkQ619Fs7K9NP7gTkoDY/WrWrKPqRW7sKE4OvdQxjaKB4C6VxgsDjVZY58ypK1wk2vMFl5SBFIaoeRBbXC0rOUXVhTHuG7lywJfDwV/N8tAare7nZgT1aD+jSF7s1IVFdxAS/DgJJOxPzV1nx6G/+JzgxElXGpKqjkGe6JMCkVH3X3bPCP1RYNBsrgkypMAV4FEx+N4RZ6aPeLPwKYlSJTc6c9A6tJeCW9QuKXQFyI7Bdy8O256gEHP7v9ua/MDKlSMBdRJjEmxdNksle/B+blFnVYjRMLOfJ4KbBxiApSiYOvxRkl3h70neICHValeM3VWRcQxcCObO+mLptyL/6CPPJbiq5zZDQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi
    type: Opaque

